name: Eclipsera CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Verify vendor integrity
        run: python scripts/check_vendor_integrity.py --verbose
      - name: Generate encode/decode fixtures
        run: python scripts/run_roundtrip.py
